Algoritmo "COMPARAÇÃO DE NÚMEROS"

Var

n1, n2: inteiro

Inicio

escreval("--- SISTEMA DE COMPARAÇÃO DE NÚMEROS ---")

escreval ("DIGITE O PRIMEIRO NÚMERO: ")
leia(n1)

escreval ("DIGITE O SEGUNDO NÚMERO: ")
leia(n2)

escreval("OS NÚMEROS SÃO:" , n1 , "e" , n2)

se n1=n2 entao
escreval ("os números SÃO IGUAIS")
senao
     se n1 < n2 entao
escreval ("o número:" , n1 , "é MENOR que" , n2)
senao
     se n1 > n2 entao
escreval ("o número:" , n1 , "é MAIOR que" , n2)
fimse
fimse
fimse
Fimalgoritmo